fixtures:
  forge_modules:
    stdlib:
      repo: 'puppetlabs/stdlib'
      ref: '9.6.0'
    archive:
      repo: 'puppet/archive'
      ref: '7.1.0'
    augeas_core:
      repo: 'puppetlabs/augeas_core'
      ref: '1.5.0'
  symlinks:
    bamboo: "#{source_dir}"
